The important information is stored in the .env file
ContriHUB/Binod-Merchandise pull request #6
Opened 2023-10-08 18:20 UTC by shivansh196

## Description

 The important information have been stored in the the .env file, which could be accessed using  os.getenv. Also the .env file has been updated in the gitignore file, as this file should not be uploaded on the github repo.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

## Checklist:

- [x ] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x ] My code follows the code style of this project.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

2023-10-09 06:15 UTC, PriyavKaneria commented
PR is not directed correctly, check from and to
Also make a PR verify request on contrihub

2023-10-09 06:52 UTC, PriyavKaneria requested changes
Use more developer friendly ENV variable name like `CONTACT_EMAIL` & `CONTACT_PASSWORD`

2023-10-09 16:20 UTC, shivansh196 commented
I have made the changes in the variables and in the request ( it is from my fork repo's "secure" branch to contrihub's main ), is it correct?

2023-10-10 04:32 UTC, PriyavKaneria commented on api/app/__init__.py
> +CONTACT_EMAIL = os.getenv("EMAIL")
As i mentioned the environment variable itself should be developer friendly so developer understands it when he puts it in ENV.
`os.getenv("CONTACT_EMAIL")`
Code variables are good for maintainers to understand but user first.

2023-10-10 04:35 UTC, PriyavKaneria requested changes
Please check comments. Also do a test run even after making changes if everything works or not. This time the issue was easily identified, it might not be the case everytime.
Thoroughly tested code should be sent for review

2023-10-10 04:35 UTC, PriyavKaneria commented on api/app/api.py
> +    CONTACT_EMAIL = EMAIL,
Did you run the changes and check? CONTACT_EMAIL is not a parameter for the Connection Config function

2023-10-10 04:35 UTC, PriyavKaneria commented on api/app/__init__.py
> +CONTACT_EMAIL = os.getenv("EMAIL")
As i mentioned the environment variable itself should be developer friendly so developer understands it when he puts it in ENV.
`os.getenv("CONTACT_EMAIL")`
Code variables are good for maintainers to understand but user first.

2023-10-10 04:35 UTC, PriyavKaneria commented on api/app/api.py
> +EMAIL = os.getenv("EMAIL")
If you are using __init__ file to get the env variables you can import them directly, why re-fetch them?

2023-10-12 04:22 UTC, PriyavKaneria commented
@shivansh196 Any updates on this?

2023-10-13 07:26 UTC, PriyavKaneria commented
Closing due to inactivity

2023-10-13 07:26 UTC, closed without merging