Add readme, requirements.txt
ContriHUB/Binod-Merchandise pull request #7
Opened 2023-10-09 13:39 UTC by akshatvermavi

Readme.md, requirement.txt is added now user can easy setup the project locally and run and able to work over it

2023-10-10 04:41 UTC, PriyavKaneria requested changes
Readme is good, please add the requirements file itself as mentioned in the issue description after  understanding the python code

2023-10-11 03:27 UTC, akshatvermavi commented
requirements file itself as mentioned in the issue description after
understanding the python code is now added after careful reading the python
code sir now you can check and review my contributions


On Tue, Oct 10, 2023 at 10:11 AM Priyav K Kaneria ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Readme is good, please add the requirements file itself as mentioned in
> the issue description after understanding the python code
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ContriHUB/Binod-Merchandise/pull/7#pullrequestreview-1666136005>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXUFZN6BQ7KW2VTPFORTAGTX6TGXJAVCNFSM6AAAAAA5Y2PGN2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRWGEZTMMBQGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-13 07:47 UTC, PriyavKaneria commented
Any updates on this? The requirements.txt file is not yet pushed

2023-10-13 09:33 UTC, akshatvermavi commented
Sir I created that txt file and pushed it as well but may be some technical
issue it's not showing up so I am going tho push once again by evening
after my classes

On Fri, Oct 13, 2023, 13:17 Priyav K Kaneria ***@***.***>
wrote:

> Any updates on this? The requirements.txt file is not yet pushed
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ContriHUB/Binod-Merchandise/pull/7#issuecomment-1761061814>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXUFZN4YGUFWRWWWHPN7AZDX7DWZBANCNFSM6AAAAAA5Y2PGNY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-14 13:44 UTC, PriyavKaneria requested changes
Shift file to api folder and it should be done

2023-10-14 13:44 UTC, PriyavKaneria commented on requirements.txt
> +attrs==22.2.0
It should be in api folder

2023-10-14 14:32 UTC, akshatvermavi commented
Sir now is this in the right position?

![Screenshot from 2023-10-14 19-58-07](https://github.com/ContriHUB/Binod-Merchandise/assets/99114167/cf651236-a2a9-4526-b075-5b210a6ecf47)

2023-10-14 17:22 UTC, PriyavKaneria approved these changes
Lgtm

2023-10-14 17:22 UTC, merged

2023-10-19 06:27 UTC, PriyavKaneria commented
Fixes #1